### ISSUE TITLE
Fill in remaining game state management interface, refactor

### ISSUE THREAD

**Issue by alexcavalli** [alexcavalli/wikitrivia#18]
Update the Game agent code to handle all the remaining events and refactor the codebase to be more consistent.

All events:
  * Timer-based:
    * Start question answering period
      * This will add/replace a question to the state
      * This will also clear any previous user answers from the state
    * Stop question answering period
      * Award points based on answer correctness
      * Mark winner(s) if we're done
  * User-event based:
    * If during question answering period
      * Mark answer choice for user (does nothing if user already marked a choice)
        * This broadcasts updated state if state changed
    * During lobby
      * Submit user name
      * Start

I am inclined to think that all events, or perhaps just the user-based events, should check for state change on event and return an indication one way or the other. This will allow us to avoid sending false updates more easily (e.g. if a user submits an answer selection but we've already moved out of the answering question phase, this should be a no-op).

**Comment by alexcavalli** [comment]
@denheck (we can talk about this in person, but just to get this written down:)

Before I get too much further on implementing all this stuff, would like your feedback on what I'm thinking. 

I'm having a bit of a hard time deciding how much to denormalize the game state to make it easier on the UI end (but obviously harder on the backend). Right now I'm not doing much. This is the state as I've got it currently (brace yourself):

```elixir
   %{
      name: game_name,
      questions: [], # a list of random questions from the db, fetched on game creation
      num_questions: , # could be removed, = questions.length
      current_question: , # 0 indexed, index into questions list
      player_names: %{}, # player_id => player_name map
      player_answers: [], # see below
      scores: %{}, # player_id => total_score
      game_phase: :lobby, # sort of a master key for the game state, probably corresponds 1-1 with UI "screens"
      phase_start_time: # a timestamp exclusively used to calculate points for players on question answering
    }
``` 

The most complex bit there I think is the player_answers bit, which is a list of maps, like this:
```elixir
[
  %{ # for question index 0
    player_id => %{answer:, time_left:}, 
    other_player_id => %{answer:, time_left: }
  }, 
  %{ # for question index 1
    player_id => %{answer:, time_left:}, 
    other_player_id => %{answer:, time_left: }
  }
]
```

The intention is to store all the answers from all the players for the whole game, so at the end a "summary" can easily be produced.

My other thought, then, was to have handle_out do some denormalization (in addition to removing sensitive information that we don't want the clients to have, e.g. future questions, question answers).I imagine that we might want so much denormalization there that handle_out is actually constructing a completely new state object using selected properties from the internal game state (and maybe that's OK). (i.e. rather than redacting stuff from the state, it's just building some other thing from bits of the state that it needs.)

I have considered denormalizing the "current question" data out in the internal state, just to make some of the backend logic a bit easier. I.e. maybe something like this:

```elixir
%{the_rest_of_state,
  current_question_data: %{
    question: %{}, # the question from questions, according to the current question index,
    player_answers: %{} # player_id => %{answer:, time_of_answer:}, for use in calculating points
  } 
}
```

And then when that question phase is over, doing points calculations from that data, and then moving the player_answers info into the top level `player_answers` array (and cleaning out the current_question_data). 

The TLDR here is, this internal state object feels like it's getting pretty complicated pretty quickly, and it doesn't really feel like it should be (or, alternatively, it feels like it's complicated enough that I might start separating "stuff that handles events on the Agent" and "stuff that takes current state and produces new state" into two different places, with the former calling/using the latter). 

How does this state feel to you? Too much? Any obvious simplifications?

Here's, I think, the complete list of events that can alter the game state (and how):
```elixir
  # * Timer-based:
  #   * Start question answering period
  #     * Phase -> question
  #     * Update the current_question value
  #     * Could do more things if the current_question_data is cached at the top level.
  #   * Stop question answering period
  #     * phase -> question_results or to game_results, depending
  #     * Award points based on answer correctness
  #     * Mark winner(s) if we're done (or maybe the frontend can do this?)
  # * User-event based:
  #   * If during question answering period
  #     * Mark answer choice for player (does nothing if player already marked a choice)
  #   * During lobby
  #     * Add player (add a player id, no change if player id already exists)
  #     * Update player name (set the player name)
  #     * Start the game (starts the first question answering phase, phase -> question)
```

**Comment by denheck** [comment]
I think this looks good and the SPA will be easier to implement with the state updates you included above.
