### ISSUE TITLE
Change DB structure

### ISSUE THREAD

**Issue by alexcavalli** [alexcavalli/wikitrivia#2]
Switch things around a bit to look more like this:

**questions**
- original (original_description?) (str)
- redacted (str) 
- answer_id (ref)

**answers**
- answer (or...something)

**some kind of many to many join table here**
Represents the answer options for a question. Either named conventionally, e.g. answers_questions, or named descriptively, e.g. answer_choices

Also update the mix tasks to populate these structures.

**Comment by denheck** [comment]
Added PR #13

**Comment by denheck** [comment]
Fixed in PR #13
