### ISSUE TITLE
Invitation page prototyping/channels work

### ISSUE THREAD

**Issue by alexcavalli** [alexcavalli/wikitrivia#4]
Need to prototype "phoenix channels based on a parameter in the url". So, given a page at a location like this

/game/1a2b3c4e

Make a page where:
* Upon visiting you're assigned a random number/name, which is displayed on the page
* Anyone else who is simultaneously visiting that page can see your random number in a list (i.e. how you might see the others in a chat room)
* You can see all the random numbers of anyone else on the page
* Anyone visiting a page with a different id (/game/:id) only sees users also on that different id

**Comment by denheck** [comment]
@alexcavalli I added a rough draft of what you described above here https://github.com/alexcavalli/wikitrivia/pull/6. 

To demo, visit http://localhost:4000/games/12345 and open the JS console. Visit that same URL multiple times in another window and you will see the usernames displayed in the JS console. 

Before getting too much further we need to figure out where we will put the game state. A potential option is we use an Agent (https://medium.com/@miguel.coba/building-a-game-with-phoenix-channels-a3e6b390cfcc). Let me know what you think.

**Comment by alexcavalli** [comment]
@denheck I think your rough draft basically covers the prototyping needs that were this issue. Shall we close this one, or was there more you wanted to do here?

**Comment by denheck** [comment]
@alexcavalli I think we can close this out
