### ISSUE TITLE
Mechanism to handle game state

### ISSUE THREAD

**Issue by alexcavalli** [alexcavalli/wikitrivia#7]
We need a mechanism for storing/updating/reading game state. Since it's pretty ephemeral (at least at the moment) an Agent will probably do. OTOH the mechanism will need to be able to handle state for multiple games at once, so we might need multiple agents: one for looking up a reference to an individual game agent by game id, and another to do all the other game-state-related functions. Or I do see that Elixir has a "Registry" which sounds a bit like the former https://hexdocs.pm/elixir/Registry.html#content

Things (maybe) needed (better naming):
get_game(game_id) -> returns some game state wrapper

On a game state wrapper:
add_player(player_id) -> adds a player to a player set, includes a name, gives them 0 points
award_points(player_id, points) -> adds points to a player's points total
get_scores() -> returns the player score data

I think that's all that's initially needed. Maybe a structure like this?

```
{
  <player_id>: {name: "Name", score: 10},
  <player_id_2>: {etc.}
}
```

**Comment by alexcavalli** [comment]
I was wrong, the state management thing I'd written was for a snake game, not for this, but it did use an Agent. Pretty easy to do, but in this case there's only one "game" to manage, whereas in our case we have many:

```elixir
defmodule SnakeGame.GameState do
  @initial_state %{
    board_size: 20,
    snake_direction: :right,
    snake_cells: [{3, 2}, {2, 2}],
    food: {5, 5}
  }
  @valid_dirs [:up, :down, :left, :right]

  def start_link do
    Agent.start_link(fn -> @initial_state end, name: __MODULE__)
  end

  def get do
    Agent.get(__MODULE__, fn s -> s end)
  end

  def reset do
    Agent.update(__MODULE__, fn _ -> @initial_state end)
  end

  def turn_snake(dir) when dir in @valid_dirs do
    Agent.update(__MODULE__, &Map.put(&1, :snake_direction, dir))
  end

  def tick do
    Agent.update(__MODULE__, &update_snake(&1))
  end

  defp update_snake(state) do
    state
    |> update_tail_position
    |> update_head_position
  end

  # When snake head is on food, move food (and don't pop tail, thus increasing snake length)
  defp update_tail_position(state = %{board_size: board_size, food: snake_head, snake_cells: [snake_head | _rest]}) do
    x = :rand.uniform(board_size - 1) + 1
    y = :rand.uniform(board_size - 1) + 1
    Map.put(state, :food, {x, y})
  end

  # Otherwise leave food and pop tail (move the tail, snake length doesn't change)
  defp update_tail_position(state = %{snake_cells: snake_cells}) do
    snake_cells = :queue.from_list(snake_cells)
    {_, snake_cells} = :queue.out_r(snake_cells)
    snake_cells = :queue.to_list(snake_cells)
    Map.put(state, :snake_cells, snake_cells)
  end

  defp update_head_position(state = %{snake_direction: dir, snake_cells: snake_cells = [head | _rest]}) do
    snake_cells = :queue.from_list(snake_cells)
    new_head = compute_new_head(head, dir)
    snake_cells = :queue.in_r(new_head, snake_cells)
    snake_cells = :queue.to_list(snake_cells)
    Map.put(state, :snake_cells, snake_cells)
  end

  defp compute_new_head({x, y}, dir) do
    case dir do
      :up -> {x, y - 1}
      :down -> {x, y + 1}
      :right -> {x + 1, y}
      :left -> {x - 1, y}
    end
  end
end
```

**Comment by denheck** [comment]
@alexcavalli the registry approach sounds like a good plan. Roughly I think the workflow might be something like:
1. A new game is started. This registers the agent for that game:
```elixir
game_id = Ecto.UUID.generate
name = {:via, Registry, {Registry.Games, game_id}}
{:ok, _} = Agent.start_link(fn -> %{} end, name: name)
```
2. Player joins a game and the state is updated triggering a broadcast of the new state:
```elixir
  def join("game:" <> game_id, _message, socket) do
    socket = assign(socket, :game_id, game_id)
    name = {:via, Registry, {Registry.Games, game_id}}
    Agent.update(name, fn %{:players => players} = state -> %{ state | :players => MapSet.put(players, "new_player_name")} end)
    send(self, :state_updated)
    {:ok, socket}
  end

def handle_info(:state_updated, socket) do
    game_id = socket.assigns.game_id
    name = {:via, Registry, {Registry.Games, game_id}}
    
    broadcast! socket, "game:state_updated", Agent.get(name, fn state -> state end)
    {:noreply, socket}
end
```
3. Agent is stopped and removed from registry once game is finished or all players leave the game

**Comment by alexcavalli** [comment]
@denheck I didn't link it up to the channel bits yet, but here's a possible interface prototype
https://github.com/alexcavalli/wikitrivia/pull/8
